### ISSUE TITLE
outdated references in README.md

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-client-examples#24]
These defines are mentioned in README.md, but do not specifically appear in the code (main.cpp or security.h).
CONN_MODE
MBED_SERVER_PORT

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTCLT-374

**Comment by yogpan01** [comment]
Please check the documentation in TechCon-release branch. There is no mention of the above listed comments.
The branch will be merged to "master" branch after OOB testing rounds.

**Comment by yogpan01** [comment]
Not valid issue, the instructions are in master branch, which will change once the TechCon-release branch will be merged to master.
