### ISSUE TITLE
Does not connect to the device connector

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbed-client-examples#25]
Setup:
Linux 14.04 LTS
Mode: Certificate
Branch: Techcon_release
HW: Frdm-k64f

ISSUE:
          i) Does not connect to mbed Device Connector (Beta)
          i) Putty does not show any trace

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-384

**Comment by yogpan01** [comment]
Please make sure you are testing against TechCon-rekease branch. The mDS address should be "ds-test-sl-dev.mbed.com" and not "api.connector.mbed.com"

**Comment by yogpan01** [comment]
This is working fine. Closing this issue.
