### ISSUE TITLE
[Defect] Error definition too vague. Should use standard Baudrate

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbed-client-examples#26]
I can't get any trace on putty using 115200. I see:
"Error Occured" only if 9600 is used.
It Should be a standard baud rate 115200 and how would I know what error is it ?
There should be a moderately elaborate error definition. This issue is linked with https://github.com/ARMmbed/mbed-client-examples/issues/25

**Comment by hasnainvirk** [comment]
This issue us linked with https://github.com/ARMmbed/mbed-client-examples/issues/25

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-383

**Comment by yogpan01** [comment]
Fixed in latest TechCon-release branch.
