### ISSUE TITLE
Compile-Linking failed in debug mode

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/mbed-client-examples#37]
I set target as frdm-k64f-armcc and build by "yotta build", it could connect/register connector successfully. For debug,  to build by ""yotta build --debug-build", I got error as "Undefined symbol platform_enter_critical". So, I implemented the undefined symbol as:
```
 // disable global interrupts
 void platform_enter_critical(void)
 { __disable_irq();}
 
 //enable global interrupts
 void platform_exit_critical(void)
 { __enable_irq();}
```
After build successfully, to run this sample by " yotta debug mbed-client-examples".
It will encounter HardFault after got IP address.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-457

**Comment by anttiylitokola** [comment]
Thanks for your report. It seems that there are couple of things missing in tracing that we must enable to get debugging work. We will let you know once that is done.

**Comment by anttiylitokola** [comment]
Hi, this has been now fixed and you should be able to compile using debug option.
