### ISSUE TITLE
release mbedos-release-15-11 should be on public yotta registry

### ISSUE THREAD

**Issue by ytsuboi** [ARMmbed/mbed-client-examples#39]
mbed-client-examples on public yotta registry is too old and doesn't works with current mbed OS release.
http://yotta.mbed.com/#/module/mbed-client-examples/0.2.2
Please update mbed-client-examples on public yotta registry to mbed-client-examples release mbedos-release-15-11.

**Comment by teetak01** [comment]
Thank you for reporting the issue. We will fix this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-497

**Comment by anttiylitokola** [comment]
mbed-client-examples should be cloned directly from github. Executables are removed from the yotta registry.
