### ISSUE TITLE
Yotta Build

### ISSUE THREAD

**Issue by ritesh2094** [ARMmbed/mbed-client-examples#76]
Once we try to build the yotta project on a MAC OS, its saying this,
1 error generated.
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed

What could be the problem? could you help me out resolving this.

![screen shot 2017-02-08 at 4 12 47 pm](https://cloud.githubusercontent.com/assets/18317097/22757653/bb8c4d48-ee19-11e6-9dc0-3670780bdb64.png)

**Comment by teetak01** [comment]
Hi @ritesh2094 MAC is not supported for this example. Also this example is very old and deprecated (See README). You should try instead our new example https://github.com/ARMmbed/mbed-os-example-client

I'll close this issue now.
