### ISSUE TITLE
not in Cache error

### ISSUE THREAD

**Issue by Timo4587** [ARMmbed/mbed-client-examples#77]
Hi I tried to build the code in yotta but it gave this error:
yotta\workspace\lib\site-packages\yotta\lib\access_common.py", line 235, in unpackFromCache
    raise NotInCache('not in cache')
yotta.lib.access_common.NotInCache: 'not in cache'

I don't know how to fix it, with other projects yotta does build perfectly.
any suggestions??

greetings Timo

**Comment by yogpan01** [comment]
Hi, This is deprecated example , please use this one https://github.com/ARMmbed/mbed-os-example-client

**Comment by BlackstoneEngineering** [comment]
@yogpan01 If its depricated it needs to be removed or marked private.
